[package]
name = "json-encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
magic-crypt = "3.1.6"
env_logger = "0.9.0"
serde_json = "1.0.81"
clap = { version = "3.1.18", features = ["derive"] }
log = "0.4.6"
